---
#
# EC2 INSTANCES
#
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create the EC2 instances
    include_role:
      name: level27tech.aws_ec2
    vars:
      aws_ec2_aws_access_key: "{{ aws_access_key }}"
      aws_ec2_aws_secret_key: "{{ aws_secret_key }}"
      aws_ec2_aws_region: "{{ aws_region }}"
      aws_ec2_name: "{{ item.name }}"
      aws_ec2_instance_type: "{{ item.type }}"
      aws_ec2_subnet: "{{ item.subnet }}"
      aws_ec2_key: "{{ item.key }}"
      aws_ec2_image: "{{ item.image }}"
      aws_ec2_tag_project: "{{ project_name }}"
      aws_ec2_create_dns: "{{ use_dns }}"
      aws_ec2_dns_domain: "{{ dns_domain }}"
      aws_ec2_security_groups: "{{ item.security_groups }}"
      aws_ec2_ansible_groups: "{{ item.ansible_groups }}"
      aws_ec2_user_data: "{{ item.user_data }}"
    with_items: "{{ ec2_instances }}"

#
# OTHER
#
- hosts: jumpbox
  vars:
    ansible_ssh_private_key_file: keys/level27-ireland-keypair.pem
    ansible_user: ec2-user
  tasks:
  - name: Copy SSH keypair to the jumpbox
    copy:
      src: keys/level27-ireland-keypair.pem
      dest: /home/ec2-user/level27-ireland-keypair.pem

- hosts: sensu_client
  vars:
    ansible_ssh_private_key_file: keys/level27-ireland-keypair.pem
    ansible_user: ec2-user
  tasks:
  - name: Install and configure sensu client
    include_role:
      name: level27tech.sensu_client
    vars:
      sensu_client_name: "{{ ansible_hostname }}"
      sensu_client_address: "{{ ansible_default_ipv4.address }}"
      sensu_client_socket_bind: "{{ ansible_default_ipv4.address }}"
      sensu_client_socket_port: 3030
      sensu_client_transport_reconnect_on_error: "true" 

